# Generated by Django 5.2.6 on 2025-09-13 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(help_text='Display name for your art', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Tell people about yourself and your art', max_length=500)),
                ('specialty', models.CharField(choices=[('painter', 'Painter'), ('sculptor', 'Sculptor'), ('digital_artist', 'Digital Artist'), ('photographer', 'Photographer'), ('mixed_media', 'Mixed Media Artist'), ('illustrator', 'Illustrator'), ('other', 'Other')], default='other', max_length=20)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner (0-2 years)'), ('intermediate', 'Intermediate (3-5 years)'), ('experienced', 'Experienced (6-10 years)'), ('professional', 'Professional (10+ years)')], default='beginner', max_length=20)),
                ('website', models.URLField(blank=True, help_text='Your personal website or portfolio')),
                ('instagram', models.CharField(blank=True, help_text='Instagram username (without @)', max_length=100)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.CharField(blank=True, help_text='Twitter username (without @)', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='artist_profiles/')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by ARTO team')),
                ('accepts_commissions', models.BooleanField(default=False, help_text='Available for custom work')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artist Profile',
                'verbose_name_plural': 'Artist Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_artist', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('newsletter_subscription', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
